name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -  name: Check out the code
         uses: actions/checkout@v4
      -  name: Set up Python
         uses: actions/setup-python@v5
         with: 
           python-version: "3.11" 
      -  name: Set up Java
         uses: actions/setup-java@v4
         with:
           distribution: temurin
           java-version: "17"
      -  name: Install dependencies
         run: |
           pip install pipenv
           pipenv install --deploy
      -  name: Run unit tests
         run: pipenv run pytest -v

